services:
  - type: web
    name: shopverse
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn shopverse.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
